# File: azure-template-publish-job.yml
# Date: 8-Jul-2019 jdw split out from original pipeline

parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
- job: ${{ format('publish_{0}_{1}', parameters.tox, parameters.os) }}
  pool:
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: 'macOS-10.14'
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-latest'
  dependsOn:
  - ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  #
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.python }}
        addToPath: true
      displayName: setup python
    #
    #- checkout: self
    #  submodules: true
    #
    - download: current
      artifact: ${{ format('sw_{0}_{1}', parameters.tox,  parameters.os) }}
    #
    - script: ls -lR $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}
      displayName: "Listing of downloaded artifacts"
    #
    - script: python -m pip install --upgrade pip twine setuptools wheel
      displayName: 'Install packaging tools'
    #
    - task: TwineAuthenticate@0
      inputs:
        externalFeeds: pypi-pub
    # Try upload
    - bash: |
        sudo cat $(PYPIRC_PATH)
        sudo cat $(PYPIRC_PATH) | sed "s/^username.*$/username=westbrook/g"
        sudo cat $(PYPIRC_PATH) | sed "s/^username.*$/username=westbrook/g" > $(System.DefaultWorkingDirectory)/.pypirc
        sudo cat $(System.DefaultWorkingDirectory)/.pypirc
        #
        pw = `grep password $(PYPIRC_PATH) | sed 's/password=//g'`
        un = `grep usernamee $(PYPIRC_PATH) | sed 's/username=//g'`
        rp = `grep repository $(PYPIRC_PATH) | sed 's/repository=//g'`
        #
        echo $pw, $un, $rp

      displayName: "What is going on here"
    - script: twine upload --verbose --skip-existing -r pypi  --config-file $(System.DefaultWorkingDirectory)/.pypirc  $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}/*
      displayName: "Upload sdist and wheel to PyPi ..."
    #
